/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author rongrong
 */
public class Frame15 extends javax.swing.JFrame {

    /**
     * Creates new form Frame15
     */
     public Frame15(String nama, String kelas, String judul, String tanggal, String tanggal2) {
        initComponents();
        Nama.setText(nama);
        Kelas.setText(kelas);
        Judul.setText("Anda meminjam buku berjudul " +judul);
        Pinjam.setText("Anda meminjam pada "+tanggal);
        Kembali.setText("Anda Harus mengembalikan pada "+tanggal2);
    }

    //Frame15(String nama, String kelas, String judul, String tanggal, String tanggal1) {
      //  throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    //}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Kelas = new javax.swing.JLabel();
        Pinjam = new javax.swing.JLabel();
        Nama = new javax.swing.JLabel();
        Kembali = new javax.swing.JLabel();
        Judul = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        Kelas.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        Kelas.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(Kelas);
        Kelas.setBounds(80, 180, 570, 30);

        Pinjam.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        Pinjam.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(Pinjam);
        Pinjam.setBounds(80, 240, 570, 30);

        Nama.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        Nama.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(Nama);
        Nama.setBounds(80, 150, 570, 30);

        Kembali.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        Kembali.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(Kembali);
        Kembali.setBounds(80, 270, 570, 30);

        Judul.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        Judul.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(Judul);
        Judul.setBounds(80, 210, 570, 30);

        jButton1.setText("OK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(280, 340, 120, 50);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/DP.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(-10, 0, 720, 474);

        setBounds(0, 0, 727, 519);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        new Frame1().setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frame15.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frame15.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frame15.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frame15.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new Frame15().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Judul;
    private javax.swing.JLabel Kelas;
    private javax.swing.JLabel Kembali;
    private javax.swing.JLabel Nama;
    private javax.swing.JLabel Pinjam;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
